name: Automated AI Content Deploy
on:
  schedule:
    - cron: '15 */3 * * *'
  push:
    branches:
      - main
    paths-ignore:
      - 'about.html'
      - 'README.md'
      - 'past_topics.txt' # If you want to update this manually without triggering the engine
  workflow_dispatch:
